apiVersion: storage.cloud.atomix.io/v1beta1
kind: RaftStorageClass
metadata:
    name: raft
spec:
  clusters: 1
  replicas: 3
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: cloud.atomix.io/v1beta3
kind: Database
metadata:
  name: raft
spec:
  partitions: 3
  storageClass:
    group: storage.cloud.atomix.io
    version: v1beta1
    kind: RaftStorageClass
    name: raft
