apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftsessionconfigs.storage.cloud.atomix.io
spec:
  group: storage.cloud.atomix.io
  names:
    kind: RaftSessionConfig
    listKind: RaftSessionConfigList
    plural: raftsessionconfigs
    singular: raftsessionconfig
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          syncReads:
            type: boolean
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiraftprotocols.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: MultiRaftProtocol
    listKind: MultiRaftProtocolList
    plural: multiraftprotocols
    singular: multiraftprotocol
  scope: Namespaced
  versions:
  - name: v2beta2
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
                default: 1
              groups:
                type: integer
                minimum: 1
                maximum: 1024
                default: 1
              image:
                type: string
              imagePullPolicy:
                type: string
              imagePullSecrets:
                type: array
                items:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
              securityContext:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              volumeClaimTemplate:
                x-kubernetes-preserve-unknown-fields: true
                type: object
              raft:
                type: object
                properties:
                  quorumSize:
                    type: integer
                  readReplicas:
                    type: integer
                  heartbeatPeriod:
                    type: string
                  electionTimeout:
                    type: string
                  snapshotEntryThreshold:
                    type: integer
                    minimum: 0
                  compactionRetainEntries:
                    type: integer
                    minimum: 0
          status:
            type: object
            properties:
              revision:
                type: integer
              replicas:
                type: array
                items:
                  type: object
                  required:
                  - id
                  - host
                  - port
                  properties:
                    id:
                      type: string
                    nodeId:
                      type: string
                    host:
                      type: string
                    port:
                      type: integer
                    extraPorts:
                      type: object
                      additionalProperties:
                        type: integer
                    ready:
                      type: boolean
              partitions:
                type: array
                items:
                  type: object
                  required:
                  - id
                  - replicas
                  properties:
                    id:
                      type: integer
                      minimum: 1
                    host:
                      type: string
                    port:
                      type: integer
                    replicas:
                      type: array
                      items:
                        type: string
                    readReplicas:
                      type: array
                      items:
                        type: string
                    ready:
                      type: boolean
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiraftclusters.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: MultiRaftCluster
    listKind: MultiRaftClusterList
    plural: multiraftclusters
    singular: multiraftcluster
  scope: Namespaced
  versions:
  - name: v2beta2
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
                default: 1
              groups:
                type: integer
                minimum: 1
                maximum: 1024
                default: 1
              image:
                type: string
              imagePullPolicy:
                type: string
              imagePullSecrets:
                type: array
                items:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string
              securityContext:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              volumeClaimTemplate:
                x-kubernetes-preserve-unknown-fields: true
                type: object
              raft:
                type: object
                properties:
                  quorumSize:
                    type: integer
                  readReplicas:
                    type: integer
                  heartbeatPeriod:
                    type: string
                  electionTimeout:
                    type: string
                  snapshotEntryThreshold:
                    type: integer
                    minimum: 0
                  compactionRetainEntries:
                    type: integer
                    minimum: 0
          status:
            type: object
            properties:
              state:
                type: string
                default: NotReady
    additionalPrinterColumns:
    - name: Status
      type: string
      description: The Raft cluster state
      jsonPath: .status.state
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftgroups.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: RaftGroup
    listKind: RaftGroupList
    plural: raftgroups
    singular: raftgroup
  scope: Namespaced
  versions:
  - name: v2beta2
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            properties:
              groupId:
                type: integer
                minumum: 1
              quorumSize:
                type: integer
              readReplicas:
                type: integer
              heartbeatPeriod:
                type: string
              electionTimeout:
                type: string
              snapshotEntryThreshold:
                type: integer
                minimum: 0
              compactionRetainEntries:
                type: integer
                minimum: 0
          status:
            type: object
            properties:
              state:
                type: string
                default: NotReady
              leader:
                type: string
              term:
                type: integer
    additionalPrinterColumns:
    - name: Leader
      type: string
      description: The current leader for the partition
      jsonPath: .status.leader
    - name: Term
      type: integer
      description: The current term for the partition
      jsonPath: .status.term
    - name: Status
      type: string
      description: The partition state
      jsonPath: .status.state
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftmembers.storage.atomix.io
spec:
  group: storage.atomix.io
  names:
    kind: RaftMember
    listKind: RaftMemberList
    plural: raftmembers
    singular: raftmember
  scope: Namespaced
  versions:
  - name: v2beta2
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - podName
            properties:
              podName:
                type: string
              readOnly:
                type: boolean
          status:
            type: object
            properties:
              state:
                type: string
                default: NotReady
              role:
                type: string
              leader:
                type: string
              term:
                type: integer
              index:
                type: integer
              lastUpdated:
                type: string
                format: date-time
              lastSnapshotIndex:
                type: integer
              lastSnapshotTime:
                type: string
                format: date-time
    additionalPrinterColumns:
    - name: Role
      type: string
      description: The member role
      jsonPath: .status.role
    - name: Leader
      type: string
      description: The current leader on the member
      jsonPath: .status.leader
    - name: Term
      type: integer
      description: The current term on the member
      jsonPath: .status.term
    - name: Snapshot Index
      type: integer
      description: The index at which the member last took a snapshot
      jsonPath: .status.lastSnapshotIndex
    - name: Snapshot Time
      type: string
      description: The last time the member took a snapshot
      jsonPath: .status.lastSnapshotTime
    - name: Status
      type: string
      description: The member state
      jsonPath: .status.state
---
apiVersion: atomix.io/v2beta1
kind: StoragePlugin
metadata:
  name: raft.storage.atomix.io
spec:
  protocol:
    group: storage.atomix.io
    kind: MultiRaftProtocol
  drivers:
  - version: v2beta2
    image: atomix/atomix-raft-storage-driver:v0.9.0
    config:
      group: storage.atomix.io
      kind: RaftSessionConfig
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atomix-raft-storage-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: atomix-raft-storage-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - pods/ephemeralcontainers
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - cloud.atomix.io
  - storage.cloud.atomix.io
  - atomix.io
  - primitives.atomix.io
  - storage.atomix.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: atomix-raft-storage-controller
subjects:
- kind: ServiceAccount
  name: atomix-raft-storage-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: atomix-raft-storage-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomix-raft-storage-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: atomix-raft-storage-controller
  template:
    metadata:
      labels:
        name: atomix-raft-storage-controller
    spec:
      serviceAccountName: atomix-raft-storage-controller
      containers:
      - name: controller
        image: atomix/atomix-raft-storage-controller:v0.8.3
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/atomix-controller-ready
          initialDelaySeconds: 4
          periodSeconds: 10
          failureThreshold: 1
        env:
        - name: CONTROLLER_NAME
          value: atomix-raft-storage-controller
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEFAULT_NODE_V2BETA1_IMAGE
          value: atomix/atomix-raft-storage-node:v0.8.3