apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftstorageclasses.storage.cloud.atomix.io
spec:
  group: storage.cloud.atomix.io
  names:
    kind: RaftStorageClass
    listKind: RaftStorageClassList
    plural: raftstorageclasses
    singular: raftstorageclass
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                imagePullPolicy:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 9
                  default: 1
                partitionsPerCluster:
                  type: integer
                  minimum: 1
                  maximum: 1024
                  default: 1
                volumeClaimTemplates:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      type: object
                      required:
                        - spec
                      properties:
                        metadata:
                          type: object
                          properties:
                            name:
                              type: string
                              default: ''
                        spec:
                          type: object
                          properties:
                            accessModes:
                              type: array
                              items:
                                type: string
                                default: ''
                            storageClassName:
                              type: string
                              default: ''
                            resources:
                              type: object
                              properties:
                                requests:
                                  type: object
                                  properties:
                                    storage:
                                      type: string
                                      default: ''

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: raft-storage-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - cloud.atomix.io
      - storage.cloud.atomix.io
    resources:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raft-storage-controller
subjects:
  - kind: ServiceAccount
    name: raft-storage-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: raft-storage-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raft-storage-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raft-storage-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: raft-storage-controller
  template:
    metadata:
      labels:
        name: raft-storage-controller
    spec:
      serviceAccountName: raft-storage-controller
      containers:
        - name: raft-storage-controller
          # Replace this with the built image name
          image: atomix/raft-storage-controller:latest
          ports:
            - containerPort: 60000
              name: metrics
            - containerPort: 5679
              name: control
          command:
            - raft-storage-controller
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/atomix-controller-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: CONTROLLER_NAME
              value: "raft-storage-controller"
            - name: CONTROLLER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace