// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: storage/config/config.proto

package config

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NodeType int32

const (
	NodeType_MEMBER   NodeType = 0
	NodeType_OBSERVER NodeType = 1
)

var NodeType_name = map[int32]string{
	0: "MEMBER",
	1: "OBSERVER",
}

var NodeType_value = map[string]int32{
	"MEMBER":   0,
	"OBSERVER": 1,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}

func (NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac523a84bbf07b3d, []int{0}
}

type ProtocolConfig struct {
	SessionTimeout          *time.Duration `protobuf:"bytes,1,opt,name=session_timeout,json=sessionTimeout,proto3,stdduration" json:"session_timeout,omitempty"`
	HeartbeatPeriod         *time.Duration `protobuf:"bytes,2,opt,name=heartbeat_period,json=heartbeatPeriod,proto3,stdduration" json:"heartbeat_period,omitempty"`
	ElectionTimeout         *time.Duration `protobuf:"bytes,3,opt,name=election_timeout,json=electionTimeout,proto3,stdduration" json:"election_timeout,omitempty"`
	SnapshotEntryThreshold  uint64         `protobuf:"varint,4,opt,name=snapshot_entry_threshold,json=snapshotEntryThreshold,proto3" json:"snapshot_entry_threshold,omitempty"`
	CompactionRetainEntries uint64         `protobuf:"varint,5,opt,name=compaction_retain_entries,json=compactionRetainEntries,proto3" json:"compaction_retain_entries,omitempty"`
}

func (m *ProtocolConfig) Reset()         { *m = ProtocolConfig{} }
func (m *ProtocolConfig) String() string { return proto.CompactTextString(m) }
func (*ProtocolConfig) ProtoMessage()    {}
func (*ProtocolConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac523a84bbf07b3d, []int{0}
}
func (m *ProtocolConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProtocolConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProtocolConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProtocolConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolConfig.Merge(m, src)
}
func (m *ProtocolConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProtocolConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolConfig proto.InternalMessageInfo

func (m *ProtocolConfig) GetSessionTimeout() *time.Duration {
	if m != nil {
		return m.SessionTimeout
	}
	return nil
}

func (m *ProtocolConfig) GetHeartbeatPeriod() *time.Duration {
	if m != nil {
		return m.HeartbeatPeriod
	}
	return nil
}

func (m *ProtocolConfig) GetElectionTimeout() *time.Duration {
	if m != nil {
		return m.ElectionTimeout
	}
	return nil
}

func (m *ProtocolConfig) GetSnapshotEntryThreshold() uint64 {
	if m != nil {
		return m.SnapshotEntryThreshold
	}
	return 0
}

func (m *ProtocolConfig) GetCompactionRetainEntries() uint64 {
	if m != nil {
		return m.CompactionRetainEntries
	}
	return 0
}

func init() {
	proto.RegisterEnum("atomix.raft.config.NodeType", NodeType_name, NodeType_value)
	proto.RegisterType((*ProtocolConfig)(nil), "atomix.raft.config.ProtocolConfig")
}

func init() { proto.RegisterFile("storage/config/config.proto", fileDescriptor_ac523a84bbf07b3d) }

var fileDescriptor_ac523a84bbf07b3d = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xb1, 0x6a, 0xdb, 0x40,
	0x18, 0xc7, 0x75, 0xae, 0x6b, 0xcc, 0xb5, 0xd8, 0x46, 0x94, 0x56, 0x76, 0xe1, 0x6a, 0x8a, 0x07,
	0xd3, 0x41, 0x82, 0x76, 0x29, 0x19, 0x95, 0x08, 0x42, 0xc0, 0x89, 0x51, 0x4c, 0x56, 0x71, 0x96,
	0xce, 0xd2, 0x81, 0xac, 0x4f, 0xdc, 0x9d, 0x21, 0x7e, 0x8b, 0x8c, 0x79, 0x84, 0x3c, 0x42, 0x1e,
	0x21, 0xa3, 0xc7, 0x6c, 0x49, 0xe4, 0x25, 0x8f, 0x90, 0x31, 0xe8, 0x64, 0x25, 0x19, 0x3d, 0xe9,
	0x43, 0xbf, 0xef, 0xf7, 0xff, 0xfe, 0x87, 0x7f, 0x4a, 0x05, 0x82, 0xc6, 0xcc, 0x09, 0x21, 0x5b,
	0xf0, 0x78, 0xf7, 0xb1, 0x73, 0x01, 0x0a, 0x4c, 0x93, 0x2a, 0x58, 0xf2, 0x4b, 0x5b, 0xd0, 0x85,
	0xb2, 0x2b, 0x32, 0x20, 0x31, 0x40, 0x9c, 0x32, 0x47, 0x6f, 0xcc, 0x57, 0x0b, 0x27, 0x5a, 0x09,
	0xaa, 0x38, 0x64, 0x95, 0x33, 0xf8, 0x16, 0x43, 0x0c, 0x7a, 0x74, 0xca, 0xa9, 0xfa, 0xfb, 0xfb,
	0xb9, 0x81, 0x3b, 0xd3, 0x72, 0x0a, 0x21, 0x3d, 0xd4, 0x41, 0xe6, 0x31, 0xee, 0x4a, 0x26, 0x25,
	0x87, 0x2c, 0x50, 0x7c, 0xc9, 0x60, 0xa5, 0x2c, 0x34, 0x44, 0xe3, 0x2f, 0x7f, 0xfb, 0x76, 0x75,
	0xc2, 0xae, 0x4f, 0xd8, 0x47, 0xbb, 0x13, 0x6e, 0xf3, 0xfa, 0xe1, 0x17, 0xf2, 0x3b, 0x3b, 0x6f,
	0x56, 0x69, 0xe6, 0x09, 0xee, 0x25, 0x8c, 0x0a, 0x35, 0x67, 0x54, 0x05, 0x39, 0x13, 0x1c, 0x22,
	0xab, 0xb1, 0x5f, 0x54, 0xf7, 0x4d, 0x9c, 0x6a, 0xaf, 0xcc, 0x62, 0x29, 0x0b, 0xd5, 0xc7, 0x5a,
	0x9f, 0xf6, 0xcc, 0xaa, 0xc5, 0xba, 0xd7, 0x7f, 0x6c, 0xc9, 0x8c, 0xe6, 0x32, 0x01, 0x15, 0xb0,
	0x4c, 0x89, 0x75, 0xa0, 0x12, 0xc1, 0x64, 0x02, 0x69, 0x64, 0x35, 0x87, 0x68, 0xdc, 0xf4, 0xbf,
	0xd7, 0xdc, 0x2b, 0xf1, 0xac, 0xa6, 0xe6, 0x01, 0xee, 0x87, 0xb0, 0xcc, 0x69, 0xd5, 0x43, 0x30,
	0x45, 0x79, 0xa6, 0x23, 0x38, 0x93, 0xd6, 0x67, 0xad, 0xfe, 0x78, 0x5f, 0xf0, 0x35, 0xf7, 0x2a,
	0xfc, 0x67, 0x84, 0xdb, 0xa7, 0x10, 0xb1, 0xd9, 0x3a, 0x67, 0x26, 0xc6, 0xad, 0x89, 0x37, 0x71,
	0x3d, 0xbf, 0x67, 0x98, 0x5f, 0x71, 0xfb, 0xcc, 0x3d, 0xf7, 0xfc, 0x0b, 0xcf, 0xef, 0x21, 0x77,
	0xf4, 0xf2, 0x44, 0xd0, 0x4d, 0x41, 0xd0, 0x6d, 0x41, 0xd0, 0x5d, 0x41, 0xd0, 0xa6, 0x20, 0xe8,
	0xb1, 0x20, 0xe8, 0x6a, 0x4b, 0x8c, 0xcd, 0x96, 0x18, 0xf7, 0x5b, 0x62, 0xcc, 0x5b, 0xfa, 0xad,
	0xff, 0x5e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x22, 0x7f, 0x9e, 0x26, 0x02, 0x00, 0x00,
}

func (this *ProtocolConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProtocolConfig)
	if !ok {
		that2, ok := that.(ProtocolConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SessionTimeout != nil && that1.SessionTimeout != nil {
		if *this.SessionTimeout != *that1.SessionTimeout {
			return false
		}
	} else if this.SessionTimeout != nil {
		return false
	} else if that1.SessionTimeout != nil {
		return false
	}
	if this.HeartbeatPeriod != nil && that1.HeartbeatPeriod != nil {
		if *this.HeartbeatPeriod != *that1.HeartbeatPeriod {
			return false
		}
	} else if this.HeartbeatPeriod != nil {
		return false
	} else if that1.HeartbeatPeriod != nil {
		return false
	}
	if this.ElectionTimeout != nil && that1.ElectionTimeout != nil {
		if *this.ElectionTimeout != *that1.ElectionTimeout {
			return false
		}
	} else if this.ElectionTimeout != nil {
		return false
	} else if that1.ElectionTimeout != nil {
		return false
	}
	if this.SnapshotEntryThreshold != that1.SnapshotEntryThreshold {
		return false
	}
	if this.CompactionRetainEntries != that1.CompactionRetainEntries {
		return false
	}
	return true
}
func (m *ProtocolConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProtocolConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProtocolConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompactionRetainEntries != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.CompactionRetainEntries))
		i--
		dAtA[i] = 0x28
	}
	if m.SnapshotEntryThreshold != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.SnapshotEntryThreshold))
		i--
		dAtA[i] = 0x20
	}
	if m.ElectionTimeout != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.ElectionTimeout, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(*m.ElectionTimeout):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintConfig(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x1a
	}
	if m.HeartbeatPeriod != nil {
		n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.HeartbeatPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(*m.HeartbeatPeriod):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintConfig(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x12
	}
	if m.SessionTimeout != nil {
		n3, err3 := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.SessionTimeout, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(*m.SessionTimeout):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintConfig(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedProtocolConfig(r randyConfig, easy bool) *ProtocolConfig {
	this := &ProtocolConfig{}
	if r.Intn(5) != 0 {
		this.SessionTimeout = github_com_gogo_protobuf_types.NewPopulatedStdDuration(r, easy)
	}
	if r.Intn(5) != 0 {
		this.HeartbeatPeriod = github_com_gogo_protobuf_types.NewPopulatedStdDuration(r, easy)
	}
	if r.Intn(5) != 0 {
		this.ElectionTimeout = github_com_gogo_protobuf_types.NewPopulatedStdDuration(r, easy)
	}
	this.SnapshotEntryThreshold = uint64(uint64(r.Uint32()))
	this.CompactionRetainEntries = uint64(uint64(r.Uint32()))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyConfig interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneConfig(r randyConfig) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringConfig(r randyConfig) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneConfig(r)
	}
	return string(tmps)
}
func randUnrecognizedConfig(r randyConfig, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldConfig(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldConfig(dAtA []byte, r randyConfig, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateConfig(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateConfig(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateConfig(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateConfig(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateConfig(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateConfig(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateConfig(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *ProtocolConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SessionTimeout != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.SessionTimeout)
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.HeartbeatPeriod != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.HeartbeatPeriod)
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.ElectionTimeout != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.ElectionTimeout)
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.SnapshotEntryThreshold != 0 {
		n += 1 + sovConfig(uint64(m.SnapshotEntryThreshold))
	}
	if m.CompactionRetainEntries != 0 {
		n += 1 + sovConfig(uint64(m.CompactionRetainEntries))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProtocolConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProtocolConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProtocolConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SessionTimeout == nil {
				m.SessionTimeout = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.SessionTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeartbeatPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.HeartbeatPeriod == nil {
				m.HeartbeatPeriod = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.HeartbeatPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElectionTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ElectionTimeout == nil {
				m.ElectionTimeout = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.ElectionTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotEntryThreshold", wireType)
			}
			m.SnapshotEntryThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SnapshotEntryThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompactionRetainEntries", wireType)
			}
			m.CompactionRetainEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompactionRetainEntries |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
